2023-09-07 01:39:10,601 INFO    StreamThr :163216 [internal.py:wandb_internal():86] W&B internal server running at pid: 163216, started at: 2023-09-07 01:39:10.600453
2023-09-07 01:39:10,606 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: status
2023-09-07 01:39:10,611 INFO    WriterThread:163216 [datastore.py:open_for_write():85] open: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/run-43i4aem2.wandb
2023-09-07 01:39:10,612 DEBUG   SenderThread:163216 [sender.py:send():379] send: header
2023-09-07 01:39:10,635 DEBUG   SenderThread:163216 [sender.py:send():379] send: run
2023-09-07 01:39:11,474 INFO    SenderThread:163216 [dir_watcher.py:__init__():211] watching files in: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files
2023-09-07 01:39:11,474 INFO    SenderThread:163216 [sender.py:_start_run_threads():1121] run started: 43i4aem2 with start time 1694021950.600346
2023-09-07 01:39:11,480 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: summary_record
2023-09-07 01:39:11,480 INFO    SenderThread:163216 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-07 01:39:11,487 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: check_version
2023-09-07 01:39:11,488 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: check_version
2023-09-07 01:39:11,791 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: run_start
2023-09-07 01:39:11,804 DEBUG   HandlerThread:163216 [system_info.py:__init__():31] System info init
2023-09-07 01:39:11,804 DEBUG   HandlerThread:163216 [system_info.py:__init__():46] System info init done
2023-09-07 01:39:11,804 INFO    HandlerThread:163216 [system_monitor.py:start():181] Starting system monitor
2023-09-07 01:39:11,804 INFO    SystemMonitor:163216 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-07 01:39:11,806 INFO    HandlerThread:163216 [system_monitor.py:probe():201] Collecting system info
2023-09-07 01:39:11,807 INFO    SystemMonitor:163216 [interfaces.py:start():190] Started cpu monitoring
2023-09-07 01:39:11,812 INFO    SystemMonitor:163216 [interfaces.py:start():190] Started disk monitoring
2023-09-07 01:39:11,813 INFO    SystemMonitor:163216 [interfaces.py:start():190] Started gpu monitoring
2023-09-07 01:39:11,815 INFO    SystemMonitor:163216 [interfaces.py:start():190] Started memory monitoring
2023-09-07 01:39:11,816 INFO    SystemMonitor:163216 [interfaces.py:start():190] Started network monitoring
2023-09-07 01:39:11,889 DEBUG   HandlerThread:163216 [system_info.py:probe():195] Probing system
2023-09-07 01:39:11,901 DEBUG   HandlerThread:163216 [system_info.py:_probe_git():180] Probing git
2023-09-07 01:39:11,922 DEBUG   HandlerThread:163216 [system_info.py:_probe_git():188] Probing git done
2023-09-07 01:39:11,922 DEBUG   HandlerThread:163216 [system_info.py:probe():240] Probing system done
2023-09-07 01:39:11,922 DEBUG   HandlerThread:163216 [system_monitor.py:probe():210] {'os': 'Linux-5.4.0-132-generic-x86_64-with-glibc2.35', 'python': '3.9.17', 'heartbeatAt': '2023-09-06T17:39:11.889332', 'startedAt': '2023-09-06T17:39:10.592688', 'docker': None, 'cuda': None, 'args': ('length=8s', 'epsilon=0.9', 'delta_epsilon=1e-5', 'target_update=50', 'use_wandb=true', 'reward_success=100', 'reward_fail=0', 'exp_name=dqn_with_her_100_0_8bits'), 'state': 'running', 'program': '/root/BitFlip/DQNwithHer/main.py', 'codePath': 'DQNwithHer/main.py', 'git': {'remote': 'git@github.com:chjchjchjchjchj/BitFlip.git', 'commit': '9b206e2fe233ae059e46287a86a690b023553a9a'}, 'email': 'chjchjchjchjchj2001@gmail.com', 'root': '/root/BitFlip', 'host': 'autodl-container-b06911993c-7c1fab7a', 'username': 'root', 'executable': '/root/miniconda3/envs/ling/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1412.9783359374997, 'min': 800.0, 'max': 3500.0}, 'cpu_freq_per_core': [{'current': 877.991, 'min': 800.0, 'max': 3500.0}, {'current': 1067.551, 'min': 800.0, 'max': 3500.0}, {'current': 869.537, 'min': 800.0, 'max': 3500.0}, {'current': 937.578, 'min': 800.0, 'max': 3500.0}, {'current': 1224.922, 'min': 800.0, 'max': 3500.0}, {'current': 1628.81, 'min': 800.0, 'max': 3500.0}, {'current': 2569.104, 'min': 800.0, 'max': 3500.0}, {'current': 825.247, 'min': 800.0, 'max': 3500.0}, {'current': 805.357, 'min': 800.0, 'max': 3500.0}, {'current': 800.879, 'min': 800.0, 'max': 3500.0}, {'current': 989.182, 'min': 800.0, 'max': 3500.0}, {'current': 2603.316, 'min': 800.0, 'max': 3500.0}, {'current': 800.442, 'min': 800.0, 'max': 3500.0}, {'current': 838.775, 'min': 800.0, 'max': 3500.0}, {'current': 2600.0, 'min': 800.0, 'max': 3500.0}, {'current': 1154.391, 'min': 800.0, 'max': 3500.0}, {'current': 976.093, 'min': 800.0, 'max': 3500.0}, {'current': 801.337, 'min': 800.0, 'max': 3500.0}, {'current': 801.32, 'min': 800.0, 'max': 3500.0}, {'current': 1588.537, 'min': 800.0, 'max': 3500.0}, {'current': 799.539, 'min': 800.0, 'max': 3500.0}, {'current': 829.017, 'min': 800.0, 'max': 3500.0}, {'current': 1900.613, 'min': 800.0, 'max': 3500.0}, {'current': 1531.296, 'min': 800.0, 'max': 3500.0}, {'current': 953.929, 'min': 800.0, 'max': 3500.0}, {'current': 1024.426, 'min': 800.0, 'max': 3500.0}, {'current': 800.452, 'min': 800.0, 'max': 3500.0}, {'current': 2477.089, 'min': 800.0, 'max': 3500.0}, {'current': 885.964, 'min': 800.0, 'max': 3500.0}, {'current': 1578.233, 'min': 800.0, 'max': 3500.0}, {'current': 2400.93, 'min': 800.0, 'max': 3500.0}, {'current': 800.282, 'min': 800.0, 'max': 3500.0}, {'current': 801.627, 'min': 800.0, 'max': 3500.0}, {'current': 2390.541, 'min': 800.0, 'max': 3500.0}, {'current': 1203.575, 'min': 800.0, 'max': 3500.0}, {'current': 801.76, 'min': 800.0, 'max': 3500.0}, {'current': 2600.0, 'min': 800.0, 'max': 3500.0}, {'current': 801.284, 'min': 800.0, 'max': 3500.0}, {'current': 1407.999, 'min': 800.0, 'max': 3500.0}, {'current': 800.219, 'min': 800.0, 'max': 3500.0}, {'current': 800.859, 'min': 800.0, 'max': 3500.0}, {'current': 800.882, 'min': 800.0, 'max': 3500.0}, {'current': 1585.148, 'min': 800.0, 'max': 3500.0}, {'current': 1046.547, 'min': 800.0, 'max': 3500.0}, {'current': 800.421, 'min': 800.0, 'max': 3500.0}, {'current': 1601.447, 'min': 800.0, 'max': 3500.0}, {'current': 1444.076, 'min': 800.0, 'max': 3500.0}, {'current': 2574.048, 'min': 800.0, 'max': 3500.0}, {'current': 2477.404, 'min': 800.0, 'max': 3500.0}, {'current': 800.419, 'min': 800.0, 'max': 3500.0}, {'current': 800.421, 'min': 800.0, 'max': 3500.0}, {'current': 1047.938, 'min': 800.0, 'max': 3500.0}, {'current': 861.758, 'min': 800.0, 'max': 3500.0}, {'current': 1734.105, 'min': 800.0, 'max': 3500.0}, {'current': 1698.405, 'min': 800.0, 'max': 3500.0}, {'current': 871.197, 'min': 800.0, 'max': 3500.0}, {'current': 2558.159, 'min': 800.0, 'max': 3500.0}, {'current': 1535.944, 'min': 800.0, 'max': 3500.0}, {'current': 800.254, 'min': 800.0, 'max': 3500.0}, {'current': 801.267, 'min': 800.0, 'max': 3500.0}, {'current': 800.607, 'min': 800.0, 'max': 3500.0}, {'current': 2524.683, 'min': 800.0, 'max': 3500.0}, {'current': 1096.947, 'min': 800.0, 'max': 3500.0}, {'current': 888.189, 'min': 800.0, 'max': 3500.0}, {'current': 874.189, 'min': 800.0, 'max': 3500.0}, {'current': 903.553, 'min': 800.0, 'max': 3500.0}, {'current': 883.192, 'min': 800.0, 'max': 3500.0}, {'current': 823.333, 'min': 800.0, 'max': 3500.0}, {'current': 1070.564, 'min': 800.0, 'max': 3500.0}, {'current': 1103.452, 'min': 800.0, 'max': 3500.0}, {'current': 2597.047, 'min': 800.0, 'max': 3500.0}, {'current': 800.892, 'min': 800.0, 'max': 3500.0}, {'current': 884.804, 'min': 800.0, 'max': 3500.0}, {'current': 800.434, 'min': 800.0, 'max': 3500.0}, {'current': 840.993, 'min': 800.0, 'max': 3500.0}, {'current': 2600.0, 'min': 800.0, 'max': 3500.0}, {'current': 800.079, 'min': 800.0, 'max': 3500.0}, {'current': 870.601, 'min': 800.0, 'max': 3500.0}, {'current': 2599.301, 'min': 800.0, 'max': 3500.0}, {'current': 1318.661, 'min': 800.0, 'max': 3500.0}, {'current': 1095.896, 'min': 800.0, 'max': 3500.0}, {'current': 800.908, 'min': 800.0, 'max': 3500.0}, {'current': 800.24, 'min': 800.0, 'max': 3500.0}, {'current': 1563.128, 'min': 800.0, 'max': 3500.0}, {'current': 800.14, 'min': 800.0, 'max': 3500.0}, {'current': 800.459, 'min': 800.0, 'max': 3500.0}, {'current': 800.427, 'min': 800.0, 'max': 3500.0}, {'current': 1028.255, 'min': 800.0, 'max': 3500.0}, {'current': 801.374, 'min': 800.0, 'max': 3500.0}, {'current': 994.562, 'min': 800.0, 'max': 3500.0}, {'current': 867.902, 'min': 800.0, 'max': 3500.0}, {'current': 2276.858, 'min': 800.0, 'max': 3500.0}, {'current': 881.643, 'min': 800.0, 'max': 3500.0}, {'current': 1520.107, 'min': 800.0, 'max': 3500.0}, {'current': 2515.339, 'min': 800.0, 'max': 3500.0}, {'current': 800.883, 'min': 800.0, 'max': 3500.0}, {'current': 801.32, 'min': 800.0, 'max': 3500.0}, {'current': 2511.183, 'min': 800.0, 'max': 3500.0}, {'current': 1579.373, 'min': 800.0, 'max': 3500.0}, {'current': 1586.381, 'min': 800.0, 'max': 3500.0}, {'current': 2600.232, 'min': 800.0, 'max': 3500.0}, {'current': 800.277, 'min': 800.0, 'max': 3500.0}, {'current': 927.365, 'min': 800.0, 'max': 3500.0}, {'current': 801.29, 'min': 800.0, 'max': 3500.0}, {'current': 800.429, 'min': 800.0, 'max': 3500.0}, {'current': 800.878, 'min': 800.0, 'max': 3500.0}, {'current': 1178.221, 'min': 800.0, 'max': 3500.0}, {'current': 850.82, 'min': 800.0, 'max': 3500.0}, {'current': 974.779, 'min': 800.0, 'max': 3500.0}, {'current': 1196.546, 'min': 800.0, 'max': 3500.0}, {'current': 1558.034, 'min': 800.0, 'max': 3500.0}, {'current': 1499.92, 'min': 800.0, 'max': 3500.0}, {'current': 1986.029, 'min': 800.0, 'max': 3500.0}, {'current': 1086.074, 'min': 800.0, 'max': 3500.0}, {'current': 801.764, 'min': 800.0, 'max': 3500.0}, {'current': 1046.922, 'min': 800.0, 'max': 3500.0}, {'current': 800.444, 'min': 800.0, 'max': 3500.0}, {'current': 924.063, 'min': 800.0, 'max': 3500.0}, {'current': 1004.336, 'min': 800.0, 'max': 3500.0}, {'current': 901.647, 'min': 800.0, 'max': 3500.0}, {'current': 2425.871, 'min': 800.0, 'max': 3500.0}, {'current': 1572.704, 'min': 800.0, 'max': 3500.0}, {'current': 801.325, 'min': 800.0, 'max': 3500.0}, {'current': 800.855, 'min': 800.0, 'max': 3500.0}, {'current': 800.862, 'min': 800.0, 'max': 3500.0}, {'current': 2444.484, 'min': 800.0, 'max': 3500.0}, {'current': 1218.025, 'min': 800.0, 'max': 3500.0}, {'current': 883.794, 'min': 800.0, 'max': 3500.0}], 'disk': {'total': 30.0, 'used': 11.524158477783203}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 4, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 377.53807830810547}}
2023-09-07 01:39:11,922 INFO    HandlerThread:163216 [system_monitor.py:probe():211] Finished collecting system info
2023-09-07 01:39:11,922 INFO    HandlerThread:163216 [system_monitor.py:probe():214] Publishing system info
2023-09-07 01:39:11,922 DEBUG   HandlerThread:163216 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-09-07 01:39:11,923 DEBUG   HandlerThread:163216 [system_info.py:_save_pip():67] Saving pip packages done
2023-09-07 01:39:11,923 DEBUG   HandlerThread:163216 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-09-07 01:39:11,930 ERROR   HandlerThread:163216 [system_info.py:_save_conda():85] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/system/system_info.py", line 81, in _save_conda
    subprocess.call(
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2023-09-07 01:39:11,931 DEBUG   HandlerThread:163216 [system_info.py:_save_conda():86] Saving conda packages done
2023-09-07 01:39:11,933 INFO    HandlerThread:163216 [system_monitor.py:probe():216] Finished publishing system info
2023-09-07 01:39:11,940 DEBUG   SenderThread:163216 [sender.py:send():379] send: files
2023-09-07 01:39:11,940 INFO    SenderThread:163216 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2023-09-07 01:39:11,952 DEBUG   SenderThread:163216 [sender.py:send():379] send: telemetry
2023-09-07 01:39:11,980 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: stop_status
2023-09-07 01:39:11,981 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: stop_status
2023-09-07 01:39:12,479 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/conda-environment.yaml
2023-09-07 01:39:12,480 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/requirements.txt
2023-09-07 01:39:12,480 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/wandb-metadata.json
2023-09-07 01:39:12,481 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/wandb-summary.json
2023-09-07 01:39:12,498 DEBUG   SenderThread:163216 [sender.py:send():379] send: exit
2023-09-07 01:39:12,498 INFO    SenderThread:163216 [sender.py:send_exit():584] handling exit code: 1
2023-09-07 01:39:12,498 INFO    SenderThread:163216 [sender.py:send_exit():586] handling runtime: 0
2023-09-07 01:39:12,499 INFO    SenderThread:163216 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-07 01:39:12,500 INFO    SenderThread:163216 [sender.py:send_exit():592] send defer
2023-09-07 01:39:12,500 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,501 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-07 01:39:12,501 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,501 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 0
2023-09-07 01:39:12,502 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 1
2023-09-07 01:39:12,502 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,502 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-07 01:39:12,503 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,503 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 1
2023-09-07 01:39:12,503 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 2
2023-09-07 01:39:12,503 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,504 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-07 01:39:12,504 INFO    HandlerThread:163216 [system_monitor.py:finish():190] Stopping system monitor
2023-09-07 01:39:12,506 DEBUG   SystemMonitor:163216 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-07 01:39:12,507 DEBUG   SystemMonitor:163216 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-07 01:39:12,506 INFO    HandlerThread:163216 [interfaces.py:finish():202] Joined cpu monitor
2023-09-07 01:39:12,507 DEBUG   SystemMonitor:163216 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-07 01:39:12,508 INFO    HandlerThread:163216 [interfaces.py:finish():202] Joined disk monitor
2023-09-07 01:39:12,609 INFO    HandlerThread:163216 [interfaces.py:finish():202] Joined gpu monitor
2023-09-07 01:39:12,610 INFO    HandlerThread:163216 [interfaces.py:finish():202] Joined memory monitor
2023-09-07 01:39:12,610 INFO    HandlerThread:163216 [interfaces.py:finish():202] Joined network monitor
2023-09-07 01:39:12,611 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,612 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 2
2023-09-07 01:39:12,612 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 3
2023-09-07 01:39:12,612 DEBUG   SenderThread:163216 [sender.py:send():379] send: stats
2023-09-07 01:39:12,613 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,613 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-07 01:39:12,614 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,614 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 3
2023-09-07 01:39:12,614 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 4
2023-09-07 01:39:12,614 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,615 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-07 01:39:12,615 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,615 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 4
2023-09-07 01:39:12,615 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 5
2023-09-07 01:39:12,615 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,616 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-07 01:39:12,616 DEBUG   SenderThread:163216 [sender.py:send():379] send: summary
2023-09-07 01:39:12,617 INFO    SenderThread:163216 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-07 01:39:12,617 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,617 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 5
2023-09-07 01:39:12,617 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 6
2023-09-07 01:39:12,618 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,618 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-07 01:39:12,618 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,618 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 6
2023-09-07 01:39:12,624 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: status_report
2023-09-07 01:39:12,806 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip/43i4aem2/wandb-metadata.json?Expires=1694108352&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pHiEGx5KCaLNuqOzG%2BsDs4Z3SQfd754%2FrTInVKdAoS%2FsMsW9e2GQp5z1tfyhfZdENpJxNhcAqdCjhTYN8mTVWx64XMIeQbr4ktB485HNsHEY10DWAZQReiwh3PtnClLugYjD486QLVfeBURG9iSBm36fnkgFroXzhZJS5Ap4PMbbcLMGCydnXb0HRnt7wluQkMZy2R6URVsBYIhRoF9s%2FApcJM20CeqlsFTlJ9hN1aaYpPudZKWC%2FN4vQ8PYFDqAnSMdebWptBba9UEXAxwUIZl8%2FzY9Q0XLIT5LZpMWr3kmauAvzx01jcV9LaUNpM%2BI%2FyXZX1fU73vM32b5%2FaNffQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:39:12,806 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15266'}
2023-09-07 01:39:12,806 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:39:12,913 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 7
2023-09-07 01:39:12,913 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:12,913 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-07 01:39:12,914 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:12,914 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 7
2023-09-07 01:39:13,177 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-07 01:39:13,475 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/config.yaml
2023-09-07 01:39:13,475 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/wandb-summary.json
2023-09-07 01:39:13,476 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/output.log
2023-09-07 01:39:14,507 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 8
2023-09-07 01:39:14,507 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: poll_exit
2023-09-07 01:39:14,508 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:14,508 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-07 01:39:14,508 DEBUG   SenderThread:163216 [sender.py:send_request():406] send_request: defer
2023-09-07 01:39:14,508 INFO    SenderThread:163216 [sender.py:send_request_defer():608] handle sender defer: 8
2023-09-07 01:39:14,509 INFO    SenderThread:163216 [job_builder.py:build():281] Attempting to build job artifact
2023-09-07 01:39:14,509 INFO    SenderThread:163216 [job_builder.py:_get_source_type():400] is repo sourced job
2023-09-07 01:39:14,511 INFO    SenderThread:163216 [job_builder.py:build():374] adding wandb-job metadata file
2023-09-07 01:39:14,516 INFO    SenderThread:163216 [sender.py:transition_state():612] send defer: 9
2023-09-07 01:39:14,516 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: defer
2023-09-07 01:39:14,516 INFO    HandlerThread:163216 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-07 01:39:14,517 DEBUG   SenderThread:163216 [sender.py:send():379] send: artifact
2023-09-07 01:39:15,476 INFO    Thread-12 :163216 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/files/output.log
2023-09-07 01:39:16,172 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/a13c8e91f52de3d441af5a3bca22e6cc?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZIy7hQAAY%2BIuYopUSuiXHjUD9lq1LEgF5psGY02PJB3%2FpCXZ7atgd5eEms4YLLV3Nc82QO%2BLrcBf4PtQpXK2sokncZ%2BDnCtmWA1XcPn3ZVALeSTUswscnFmqI8NOYkUUfW7leShs3mKlOK0JJOsNL6Qr%2Bon3aW8s9KiHX7RKHlYBLT%2FKz1DKchSKfRVzD%2BJqGhxfTB%2FrWDvDsVTwUrRySllXAuWdM6RAS0cJqXpPxL01EOOzKIYZd%2BfA6CO5JXQOaAPhnjKhOSwuOB8klRZVqgwq8YEbeptGNjF8ozkaIrVR1KVr5QzSP5ItJ8XyZ6Ve5qZivKTGRBWWZuegZkFVZw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:39:16,172 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'oTyOkfUt49RBr1o7yiLmzA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3147'}
2023-09-07 01:39:16,172 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:39:17,426 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/a13c8e91f52de3d441af5a3bca22e6cc?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZIy7hQAAY%2BIuYopUSuiXHjUD9lq1LEgF5psGY02PJB3%2FpCXZ7atgd5eEms4YLLV3Nc82QO%2BLrcBf4PtQpXK2sokncZ%2BDnCtmWA1XcPn3ZVALeSTUswscnFmqI8NOYkUUfW7leShs3mKlOK0JJOsNL6Qr%2Bon3aW8s9KiHX7RKHlYBLT%2FKz1DKchSKfRVzD%2BJqGhxfTB%2FrWDvDsVTwUrRySllXAuWdM6RAS0cJqXpPxL01EOOzKIYZd%2BfA6CO5JXQOaAPhnjKhOSwuOB8klRZVqgwq8YEbeptGNjF8ozkaIrVR1KVr5QzSP5ItJ8XyZ6Ve5qZivKTGRBWWZuegZkFVZw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:39:17,426 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'oTyOkfUt49RBr1o7yiLmzA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3147'}
2023-09-07 01:39:17,426 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:39:18,179 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:20,275 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/a13c8e91f52de3d441af5a3bca22e6cc?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZIy7hQAAY%2BIuYopUSuiXHjUD9lq1LEgF5psGY02PJB3%2FpCXZ7atgd5eEms4YLLV3Nc82QO%2BLrcBf4PtQpXK2sokncZ%2BDnCtmWA1XcPn3ZVALeSTUswscnFmqI8NOYkUUfW7leShs3mKlOK0JJOsNL6Qr%2Bon3aW8s9KiHX7RKHlYBLT%2FKz1DKchSKfRVzD%2BJqGhxfTB%2FrWDvDsVTwUrRySllXAuWdM6RAS0cJqXpPxL01EOOzKIYZd%2BfA6CO5JXQOaAPhnjKhOSwuOB8klRZVqgwq8YEbeptGNjF8ozkaIrVR1KVr5QzSP5ItJ8XyZ6Ve5qZivKTGRBWWZuegZkFVZw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:39:20,275 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'oTyOkfUt49RBr1o7yiLmzA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3147'}
2023-09-07 01:39:20,275 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:39:20,275 INFO    wandb-upload_1:163216 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-07 01:39:23,181 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:24,811 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/a13c8e91f52de3d441af5a3bca22e6cc?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZIy7hQAAY%2BIuYopUSuiXHjUD9lq1LEgF5psGY02PJB3%2FpCXZ7atgd5eEms4YLLV3Nc82QO%2BLrcBf4PtQpXK2sokncZ%2BDnCtmWA1XcPn3ZVALeSTUswscnFmqI8NOYkUUfW7leShs3mKlOK0JJOsNL6Qr%2Bon3aW8s9KiHX7RKHlYBLT%2FKz1DKchSKfRVzD%2BJqGhxfTB%2FrWDvDsVTwUrRySllXAuWdM6RAS0cJqXpPxL01EOOzKIYZd%2BfA6CO5JXQOaAPhnjKhOSwuOB8klRZVqgwq8YEbeptGNjF8ozkaIrVR1KVr5QzSP5ItJ8XyZ6Ve5qZivKTGRBWWZuegZkFVZw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:39:24,811 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'oTyOkfUt49RBr1o7yiLmzA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3147'}
2023-09-07 01:39:24,811 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:39:28,183 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:33,185 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:34,659 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/a13c8e91f52de3d441af5a3bca22e6cc?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZIy7hQAAY%2BIuYopUSuiXHjUD9lq1LEgF5psGY02PJB3%2FpCXZ7atgd5eEms4YLLV3Nc82QO%2BLrcBf4PtQpXK2sokncZ%2BDnCtmWA1XcPn3ZVALeSTUswscnFmqI8NOYkUUfW7leShs3mKlOK0JJOsNL6Qr%2Bon3aW8s9KiHX7RKHlYBLT%2FKz1DKchSKfRVzD%2BJqGhxfTB%2FrWDvDsVTwUrRySllXAuWdM6RAS0cJqXpPxL01EOOzKIYZd%2BfA6CO5JXQOaAPhnjKhOSwuOB8klRZVqgwq8YEbeptGNjF8ozkaIrVR1KVr5QzSP5ItJ8XyZ6Ve5qZivKTGRBWWZuegZkFVZw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:39:34,659 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'oTyOkfUt49RBr1o7yiLmzA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3147'}
2023-09-07 01:39:34,660 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:39:38,187 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:43,190 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:48,192 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:53,195 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:58,197 DEBUG   HandlerThread:163216 [handler.py:handle_request():144] handle_request: keepalive
2023-09-07 01:39:59,661 WARNING StreamThr :163216 [internal.py:is_dead():414] Internal process exiting, parent pid 163014 disappeared
2023-09-07 01:39:59,661 ERROR   StreamThr :163216 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-07 01:40:00,197 INFO    HandlerThread:163216 [handler.py:finish():861] shutting down handler
2023-09-07 01:40:00,525 INFO    WriterThread:163216 [datastore.py:close():294] close: /root/BitFlip/DQNwithHer/outputs/2023-09-07/01-39-08/wandb/run-20230907_013910-43i4aem2/run-43i4aem2.wandb
2023-09-07 01:41:23,804 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip/43i4aem2/wandb-metadata.json?Expires=1694108352&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pHiEGx5KCaLNuqOzG%2BsDs4Z3SQfd754%2FrTInVKdAoS%2FsMsW9e2GQp5z1tfyhfZdENpJxNhcAqdCjhTYN8mTVWx64XMIeQbr4ktB485HNsHEY10DWAZQReiwh3PtnClLugYjD486QLVfeBURG9iSBm36fnkgFroXzhZJS5Ap4PMbbcLMGCydnXb0HRnt7wluQkMZy2R6URVsBYIhRoF9s%2FApcJM20CeqlsFTlJ9hN1aaYpPudZKWC%2FN4vQ8PYFDqAnSMdebWptBba9UEXAxwUIZl8%2FzY9Q0XLIT5LZpMWr3kmauAvzx01jcV9LaUNpM%2BI%2FyXZX1fU73vM32b5%2FaNffQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:41:23,807 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15266'}
2023-09-07 01:41:23,807 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:41:25,866 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/07f8e77911352be688e59171fca3a30f?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A%2BQyWcYW%2FHG4q%2BiiHqUiSP1C4mvVPhFB%2FraWhvlk6%2BGYh0tiX%2FKAvEQO61llMDXWnWRr1Njm7DX%2B5%2FqoGYTXxmBs%2FoRLAx%2Fc8ZLwi%2FukTuRjGOHRWKbPsMu79IMpnXWfLrnBviFcS5x5aXuYvVIEOHGHtvOaNDpNTwk62iEOcz1p%2BLX80Ik7LDpJo3BBoJJDJI8EWc4BH4oyxI%2Fbr9rHyNrnOGiLHacY8P5BLzzyBmZWmy7MNfFBb91X5H6fQlpq7z%2BVLnbPIp3mlSlXXT5gvSJCzRXoUE2uJRV3WpHGX%2BnWiXQevBlZ%2Bg%2FNmrOTSMfQgBFFwij1s%2Fe6muA5AuXiTg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:41:25,866 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'B/jneRE1K+aI5ZFx/KOjDw==', 'Content-Type': 'application/json', 'Content-Length': '2816'}
2023-09-07 01:41:25,866 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:41:26,335 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip/43i4aem2/wandb-metadata.json?Expires=1694108352&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pHiEGx5KCaLNuqOzG%2BsDs4Z3SQfd754%2FrTInVKdAoS%2FsMsW9e2GQp5z1tfyhfZdENpJxNhcAqdCjhTYN8mTVWx64XMIeQbr4ktB485HNsHEY10DWAZQReiwh3PtnClLugYjD486QLVfeBURG9iSBm36fnkgFroXzhZJS5Ap4PMbbcLMGCydnXb0HRnt7wluQkMZy2R6URVsBYIhRoF9s%2FApcJM20CeqlsFTlJ9hN1aaYpPudZKWC%2FN4vQ8PYFDqAnSMdebWptBba9UEXAxwUIZl8%2FzY9Q0XLIT5LZpMWr3kmauAvzx01jcV9LaUNpM%2BI%2FyXZX1fU73vM32b5%2FaNffQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:41:26,336 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15266'}
2023-09-07 01:41:26,336 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:41:26,336 INFO    wandb-upload_0:163216 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-07 01:41:31,364 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip/43i4aem2/wandb-metadata.json?Expires=1694108352&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pHiEGx5KCaLNuqOzG%2BsDs4Z3SQfd754%2FrTInVKdAoS%2FsMsW9e2GQp5z1tfyhfZdENpJxNhcAqdCjhTYN8mTVWx64XMIeQbr4ktB485HNsHEY10DWAZQReiwh3PtnClLugYjD486QLVfeBURG9iSBm36fnkgFroXzhZJS5Ap4PMbbcLMGCydnXb0HRnt7wluQkMZy2R6URVsBYIhRoF9s%2FApcJM20CeqlsFTlJ9hN1aaYpPudZKWC%2FN4vQ8PYFDqAnSMdebWptBba9UEXAxwUIZl8%2FzY9Q0XLIT5LZpMWr3kmauAvzx01jcV9LaUNpM%2BI%2FyXZX1fU73vM32b5%2FaNffQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:41:31,364 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15266'}
2023-09-07 01:41:31,364 ERROR   wandb-upload_0:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:42:02,727 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/a13c8e91f52de3d441af5a3bca22e6cc?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ZIy7hQAAY%2BIuYopUSuiXHjUD9lq1LEgF5psGY02PJB3%2FpCXZ7atgd5eEms4YLLV3Nc82QO%2BLrcBf4PtQpXK2sokncZ%2BDnCtmWA1XcPn3ZVALeSTUswscnFmqI8NOYkUUfW7leShs3mKlOK0JJOsNL6Qr%2Bon3aW8s9KiHX7RKHlYBLT%2FKz1DKchSKfRVzD%2BJqGhxfTB%2FrWDvDsVTwUrRySllXAuWdM6RAS0cJqXpPxL01EOOzKIYZd%2BfA6CO5JXQOaAPhnjKhOSwuOB8klRZVqgwq8YEbeptGNjF8ozkaIrVR1KVr5QzSP5ItJ8XyZ6Ve5qZivKTGRBWWZuegZkFVZw%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:42:02,727 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'oTyOkfUt49RBr1o7yiLmzA==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3147'}
2023-09-07 01:42:02,727 ERROR   wandb-upload_1:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:43:36,921 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/07f8e77911352be688e59171fca3a30f?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A%2BQyWcYW%2FHG4q%2BiiHqUiSP1C4mvVPhFB%2FraWhvlk6%2BGYh0tiX%2FKAvEQO61llMDXWnWRr1Njm7DX%2B5%2FqoGYTXxmBs%2FoRLAx%2Fc8ZLwi%2FukTuRjGOHRWKbPsMu79IMpnXWfLrnBviFcS5x5aXuYvVIEOHGHtvOaNDpNTwk62iEOcz1p%2BLX80Ik7LDpJo3BBoJJDJI8EWc4BH4oyxI%2Fbr9rHyNrnOGiLHacY8P5BLzzyBmZWmy7MNfFBb91X5H6fQlpq7z%2BVLnbPIp3mlSlXXT5gvSJCzRXoUE2uJRV3WpHGX%2BnWiXQevBlZ%2Bg%2FNmrOTSMfQgBFFwij1s%2Fe6muA5AuXiTg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:43:36,921 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'B/jneRE1K+aI5ZFx/KOjDw==', 'Content-Type': 'application/json', 'Content-Length': '2816'}
2023-09-07 01:43:36,921 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:43:39,296 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95435813/560816586/07f8e77911352be688e59171fca3a30f?Expires=1694108355&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=A%2BQyWcYW%2FHG4q%2BiiHqUiSP1C4mvVPhFB%2FraWhvlk6%2BGYh0tiX%2FKAvEQO61llMDXWnWRr1Njm7DX%2B5%2FqoGYTXxmBs%2FoRLAx%2Fc8ZLwi%2FukTuRjGOHRWKbPsMu79IMpnXWfLrnBviFcS5x5aXuYvVIEOHGHtvOaNDpNTwk62iEOcz1p%2BLX80Ik7LDpJo3BBoJJDJI8EWc4BH4oyxI%2Fbr9rHyNrnOGiLHacY8P5BLzzyBmZWmy7MNfFBb91X5H6fQlpq7z%2BVLnbPIp3mlSlXXT5gvSJCzRXoUE2uJRV3WpHGX%2BnWiXQevBlZ%2Bg%2FNmrOTSMfQgBFFwij1s%2Fe6muA5AuXiTg%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-07 01:43:39,297 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'B/jneRE1K+aI5ZFx/KOjDw==', 'Content-Type': 'application/json', 'Content-Length': '2816'}
2023-09-07 01:43:39,297 ERROR   wandb-upload_2:163216 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-07 01:43:39,297 INFO    wandb-upload_2:163216 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
